// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AFP_Test.Infraestructura.Models
{
    public partial class Departamentos
    {
        public Departamentos()
        {
            Empresa = new HashSet<Empresa>();
        }

        public int IdDepartamento { get; set; }
        public string NombreDepartamento { get; set; }

        public string Nombre { get; set; }
        public string RazonSocial { get; set; }

        public virtual ICollection<Empresa> Empresa { get; set; }
    }
}