// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AFP_Test.Infraestructura.Models
{
    public partial class Empresa
    {
        public int IdEmpresa { get; set; }
        public string Nombre { get; set; }
        public string RazonSocial { get; set; }
        public DateTime? FechaDeRegistro { get; set; }
        public string Bitacora { get; set; }
        public int? IdDepartamento { get; set; }

        public virtual Departamentos IdDepartamentoNavigation { get; set; }
    }
}